name: Send mail
on: push
jobs:
  sendmail:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello world
        run: echo "Hello world!"
      
      - name: Send mail
        if: ${{always() }}
         uses: dawidd6/action-send-mail@v3
          with:
          server_address: smtp.example.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ${{ github.jobs}} - Job ${{ github.repository }} has ${{ job.status }} 
          body: ${{ github.jobs}} Job in workflow ${{github.workflow}} of ${{ github.repository }} has ${{ job.status }}
          to: larrytestautomation@gmail.com
          from: Larry Test Automation <
